# -*- coding: utf-8 -*-
"""py_rfid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAvMn1k7QUxlaxMDR__talkOqBbeQZUS
"""

#!/usr/bin/env python

import RPi.GPIO as GPIO
from mfrc522 import SImpleMFRC522
import time

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)

reader = SimpleMFRC522()

atual_id, text = reader.read()
atual_ts = int(time.time())
datetime = time.strtime('%A, %Y-%m-%d %H:%M:%S', time.localtime(atual_ts))

list_id = []
list_ts = []

try:
  print("Lista IDs: " + str(list_id))
  print("Lista TSs: " + str(list_ts))

  print("Informações atuais: " + str(atual_id) + ", "+ str(atual_ts) + ", " + text)

  if len(list_id) != 0:
    last_id = list_id[len(list_id) - 1]
    last_ts = list_ts[len(list_ts) - 1]
    print(list_id + "\n")
    print(list_ts + "\n")
  def isNew(list_id):
    if atual_id in list_id:
      return False
    else:
      return True
  if len(list_id) < 3:
    if isNew(list_id):
      print("Adicionar na lista!")
      list_id.append(atual_id)
      list_ts.append(atual_ts)
      print("Lista de IDs apos append: " + str(list_id))
      print("Lista de TSs apos append: " + str(list_ts))
    else:
      print("ID já existe na lista de ID, não guardar.")
  else:
    if isNew(list_id):
      first_id = list_id [0]
      first_ts = list_ts [0]
      del list_id [0]
      del list_ts [0]
      print("Lista de ID dps de del[0]: " + str(list_id))
      print("Lista de TS dps de del[0]: " + str(list_ts))
      list_id.append(atual_id)
      list_ts.append(atual_ts)
      print("Adicionando um elemento ao dataread.txt")

      print("Printando os elementos do dataread.txt")
      file = open('dataread.txt','a+')
      file.write(str(first_id) + ',' + str(first_ts) + '\n')
      file.close()
      print("Added informations.")

  print("\n\n Informações de arquivo dataread.txt")
  file_read = open('dataread.txt','r+')
  file_line = file_read.readlines()
  file_read.close()
  last_line = file_line[len(file_line) - 1]

  print("Ultima linha, antes da leitura atual: " + last_line)

  print("\n\n Informações do arquivo dataread.txt")
  for linha in file:
    linha = linha.rscript()
    print(linha)
  file.close()
finally: 
  GIPO.cleanup()

